In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:

import os
import pandas as pd
import random as rn
import numpy as np
from collections import Counter
from IPython.display import display, Image
import tensorflow as tf

In [3]:
# 딕셔너리화
image_feature_description = {
    'height': tf.io.FixedLenFeature([], tf.int64),
    'width': tf.io.FixedLenFeature([], tf.int64),
    'depth': tf.io.FixedLenFeature([], tf.int64),
    'label': tf.io.FixedLenFeature([24], tf.int64), 
    'image_raw': tf.io.FixedLenFeature([], tf.string),
}


# 사전을 이용하여 입력 tf.Example 프로토를 구문 분석
def _parse_image_function(example_proto):
    return tf.io.parse_single_example(example_proto, image_feature_description)

# tfrecord 파일을 불러옴
raw_image_dataset = tf.data.TFRecordDataset('/content/drive/MyDrive/facial_emotion_recognition_using_K-drama_dataset-main/tfrecords/multi-label_test.tfrecords')
# _parse_image_function을 이용한 raw_image_dataset 값 변경
parsed_image_dataset = raw_image_dataset.map(_parse_image_function)
parsed_image_dataset

<MapDataset element_spec={'depth': TensorSpec(shape=(), dtype=tf.int64, name=None), 'height': TensorSpec(shape=(), dtype=tf.int64, name=None), 'image_raw': TensorSpec(shape=(), dtype=tf.string, name=None), 'label': TensorSpec(shape=(24,), dtype=tf.int64, name=None), 'width': TensorSpec(shape=(), dtype=tf.int64, name=None)}>

In [ ]:
n = 0
for image_features in parsed_image_dataset.take(3882):
    image_raw = image_features['image_raw'].numpy()
    # display(Image(data=image_raw))
    n += 1
    print("Number of images displayed:", n,"===>", image_features['label'])

Number of images displayed: 1 ===> tf.Tensor([0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0], shape=(24,), dtype=int64)
Number of images displayed: 2 ===> tf.Tensor([0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0], shape=(24,), dtype=int64)
Number of images displayed: 3 ===> tf.Tensor([0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0], shape=(24,), dtype=int64)
Number of images displayed: 4 ===> tf.Tensor([0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0], shape=(24,), dtype=int64)
Number of images displayed: 5 ===> tf.Tensor([0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0], shape=(24,), dtype=int64)
Number of images displayed: 6 ===> tf.Tensor([0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0], shape=(24,), dtype=int64)
Number of images displayed: 7 ===> tf.Tensor([0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0], shape=(24,), dtype=int64)
Number of images displayed: 8 ===> tf.Tensor([0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0], shape=(24,), dtype=int64)
Number of images display